# Generated by Django 5.0.3 on 2024-04-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="doctor",
            fields=[
                ("doctor_id", models.AutoField(primary_key=True, serialize=False)),
                ("doctor_name", models.TextField()),
                ("doctor_location", models.TextField()),
                ("doctor_speciality", models.TextField()),
            ],
        ),
    ]
