# Generated by Django 5.0.3 on 2024-04-03 14:55

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        # migrations.CreateModel(
        #     name="Doctor",
        #     fields=[
        #         ("doctor_id", models.AutoField(primary_key=True, serialize=False)),
        #         ("full_name", models.TextField()),
        #         ("location", models.TextField()),
        #         ("speciality", models.TextField()),
        #     ],
        # ),
    ]
