# Generated by Django 5.0.3 on 2024-04-03 17:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("endpoints", "0002_speciality"),
    ]

    operations = [
        # migrations.RenameModel(
        #     old_name="speciality",
        #     new_name="specialty",
        # ),
        # migrations.RenameField(
        #     model_name="specialty",
        #     old_name="speciality_id",
        #     new_name="specialty_id",
        # ),
        # migrations.RenameField(
        #     model_name="specialty",
        #     old_name="speciality_name",
        #     new_name="specialty_name",
        # ),
    ]
