# Generated by Django 5.0.3 on 2024-04-12 20:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endpoints", "0003_rename_speciality_specialty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("password", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=10)),
                ("age", models.IntegerField()),
                ("height", models.IntegerField()),
                ("weight", models.IntegerField()),
                ("special_cases", models.CharField(max_length=100)),
                ("wilaya", models.CharField(max_length=100)),
            ],
        ),
    ]
