# Generated by Django 4.2.11 on 2024-04-15 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("endpoints", "0003_rename_speciality_specialty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("gender", models.CharField(max_length=10)),
                ("age", models.PositiveIntegerField()),
                ("height", models.FloatField()),
                ("weight", models.FloatField()),
                ("special_cases_1", models.CharField(max_length=100)),
                ("special_cases_2", models.CharField(max_length=100)),
                ("special_cases_3", models.CharField(max_length=100)),
                ("picture", models.ImageField(upload_to="patient_pictures/")),
                ("wilaya", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Speciality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("rating", models.DecimalField(decimal_places=2, max_digits=3)),
                ("phone_number", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("picture", models.ImageField(upload_to="doctor_pictures/")),
                ("gps_location_x", models.FloatField()),
                ("gps_location_y", models.FloatField()),
                (
                    "speciality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="endpoints.speciality",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Disease",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "speciality",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="endpoints.speciality",
                    ),
                ),
            ],
        ),
    ]
