# Generated by Django 5.0.3 on 2024-04-16 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endpoints", "0004_patient"),
    ]

    operations = [
        migrations.CreateModel(
            name="Disease",
            fields=[
                ("Disease_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Doctors",
            fields=[
                ("Doctor_id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.CharField(max_length=100)),
                ("location", models.CharField(max_length=200)),
                ("rating", models.DecimalField(decimal_places=2, max_digits=3)),
                ("phone_number", models.CharField(max_length=20)),
                ("description", models.TextField()),
                ("gps_location_x", models.FloatField()),
                ("gps_location_y", models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name="doctor",
        ),
        migrations.RenameField(
            model_name="specialty",
            old_name="specialty_name",
            new_name="description",
        ),
        migrations.RenameField(
            model_name="specialty",
            old_name="specialty_id",
            new_name="spec_id",
        ),
        migrations.AddField(
            model_name="specialty",
            name="name",
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="patient",
            name="wilaya",
            field=models.CharField(default="Algiers", max_length=100),
        ),
        migrations.AddField(
            model_name="disease",
            name="speciality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="endpoints.specialty"
            ),
        ),
        migrations.AddField(
            model_name="doctors",
            name="speciality",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="endpoints.specialty"
            ),
        ),
    ]
