# Generated by Django 5.0.3 on 2024-04-03 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endpoints", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="speciality",
            fields=[
                ("speciality_id", models.AutoField(primary_key=True, serialize=False)),
                ("speciality_name", models.TextField()),
            ],
        ),
    ]
