# Generated by Django 5.0 on 2024-04-14 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endpoints", "0003_rename_speciality_specialty_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Patient",
            fields=[
                ("patient_id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.TextField()),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("password", models.TextField()),
                (
                    "gender",
                    models.CharField(
                        choices=[("M", "Male"), ("F", "Female"), ("O", "Other")],
                        max_length=1,
                    ),
                ),
                ("age", models.IntegerField()),
                ("height", models.FloatField()),
                ("weight", models.FloatField()),
                ("special_case1", models.TextField()),
                ("special_case2", models.TextField()),
                ("special_case3", models.TextField()),
                ("picture", models.TextField()),
                ("wilaya", models.TextField()),
            ],
        ),
    ]
