# Generated by Django 5.0 on 2024-04-14 17:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endpoints", "0004_patient"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="gender",
            field=models.CharField(
                choices=[("M", "Male"), ("F", "Female")], max_length=1
            ),
        ),
    ]
