# Generated by Django 5.0 on 2024-04-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endpoints", "0005_alter_patient_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="otp",
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
