# Generated by Django 5.0 on 2024-04-24 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endpoints", "0008_patient_otp"),
    ]

    operations = [
        migrations.CreateModel(
            name="Donation",
            fields=[
                ("donation_id", models.AutoField(primary_key=True, serialize=False)),
                ("description", models.TextField()),
                ("image", models.ImageField(upload_to="donation_images/")),
                ("available", models.BooleanField(default=True)),
                ("phone_number", models.CharField(max_length=20)),
                ("wilaya", models.CharField(max_length=100)),
                (
                    "patient",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="endpoints.patient",
                    ),
                ),
            ],
        ),
    ]
