# Generated by Django 5.0 on 2024-04-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endpoints", "0009_donation"),
    ]

    operations = [
        migrations.AddField(
            model_name="patient",
            name="points",
            field=models.IntegerField(default=0),
        ),
    ]
