# Generated by Django 5.0 on 2024-04-25 03:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endpoints", "0011_donation_title"),
    ]

    operations = [
        migrations.CreateModel(
            name="Sessions",
            fields=[
                ("session_id", models.AutoField(primary_key=True, serialize=False)),
                ("session_time", models.DateTimeField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("reserved", "Reserved"),
                            ("not_reserved", "Not Reserved"),
                        ],
                        default="not_reserved",
                        max_length=20,
                    ),
                ),
                (
                    "doctor_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="endpoints.doctors",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("reservation_id", models.AutoField(primary_key=True, serialize=False)),
                ("state", models.CharField(max_length=20)),
                (
                    "patient_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="endpoints.patient",
                    ),
                ),
                (
                    "session_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="endpoints.sessions",
                    ),
                ),
            ],
        ),
    ]
