# Generated by Django 5.0 on 2024-05-02 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("endpoints", "0012_sessions_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="state",
            field=models.CharField(
                choices=[("reserved", "Reserved"), ("not_reserved", "Not Reserved")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sessions",
            name="state",
            field=models.CharField(
                choices=[
                    ("reserved", "Reserved"),
                    ("not_reserved", "Not Reserved"),
                    ("requested", "requested"),
                ],
                default="not_reserved",
                max_length=20,
            ),
        ),
    ]
